package org.mortages;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class IncomeSource  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private Integer amount;
    
    private String type;

    public IncomeSource() {
    }

    public IncomeSource(Integer amount, String type) {
        this.amount = amount;
        this.type = type;
    }


    
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(  Integer amount ) {
        this.amount = amount;
    }
    
    public String getType() {
        return this.type;
    }

    public void setType(  String type ) {
        this.type = type;
    }




}