package org.mortages;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class LoanApplication  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private Integer amount;
    
    private Boolean approved;
    
    private Integer approvedRate;
    
    private Integer deposit;
    
    private String explanation;
    
    private Integer lengthYears;
    
    private Integer insuranceCost;

    public LoanApplication() {
    }

    public LoanApplication(Integer amount, Boolean approved, Integer approvedRate, Integer deposit, String explanation, Integer lengthYears, Integer insuranceCost) {
        this.amount = amount;
        this.approved = approved;
        this.approvedRate = approvedRate;
        this.deposit = deposit;
        this.explanation = explanation;
        this.lengthYears = lengthYears;
        this.insuranceCost = insuranceCost;
    }


    
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(  Integer amount ) {
        this.amount = amount;
    }
    
    public Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(  Boolean approved ) {
        this.approved = approved;
    }
    
    public Integer getApprovedRate() {
        return this.approvedRate;
    }

    public void setApprovedRate(  Integer approvedRate ) {
        this.approvedRate = approvedRate;
    }
    
    public Integer getDeposit() {
        return this.deposit;
    }

    public void setDeposit(  Integer deposit ) {
        this.deposit = deposit;
    }
    
    public String getExplanation() {
        return this.explanation;
    }

    public void setExplanation(  String explanation ) {
        this.explanation = explanation;
    }
    
    public Integer getLengthYears() {
        return this.lengthYears;
    }

    public void setLengthYears(  Integer lengthYears ) {
        this.lengthYears = lengthYears;
    }
    
    public Integer getInsuranceCost() {
        return this.insuranceCost;
    }

    public void setInsuranceCost(  Integer insuranceCost ) {
        this.insuranceCost = insuranceCost;
    }




}