package mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Bankruptcy  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private Integer yearOfOccurrence;
    
    private Integer amountOwed;

    public Bankruptcy() {

    }
    
    public Integer getYearOfOccurrence() {
        return this.yearOfOccurrence;
    }

    public void setYearOfOccurrence(  Integer yearOfOccurrence ) {
        this.yearOfOccurrence = yearOfOccurrence;
    }
    
    public Integer getAmountOwed() {
        return this.amountOwed;
    }

    public void setAmountOwed(  Integer amountOwed ) {
        this.amountOwed = amountOwed;
    }




}